spring:
  datasource:
    url: jdbc:mysql://localhost:3306/auth_user?characterEncoding=utf-8&serverTimezone=UTC
    username: root
    password: ENC(i4+qvUO1mKlzmIlkB++s3Q==)
    driver-class-name: com.mysql.cj.jdbc.Driver
  redis:
    host: localhost
    port: 6379
    password:

server:
  port: 18080

secretKey:
  publicKey: 04ac65e37746267acd937a6532be574cf48e678f33f535b045baa92c3533892f8d66bff57cad3fe8e37a61a2693ca49c21c933c57b211e04bf104dc4a5d46aa3dc
  privateKey: ENC(JV2x3CzzjzfMnK7SOxW0HyB4wfB2LdEDf170y5SQejQBR+gNkjScGEzbNFtH+iiS64ffwZGmuHJ6+g7MutrFPVSChv17mtnPp9wzA83qLmM=)

timeOut: 360

# application.yml
jasypt:
  encryptor:
    password:
    algorithm: jasyptStringEncryptor
    stringOutputType: UTF-8
